import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Potenfyr - Minecraft Server Hosting, Game Hosting & more",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black overflow-scroll scroll-smooth">
      <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
